apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-lab
  labels:
    app: mlops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-lab
  template:
    metadata:
      labels:
        app: mlops-lab
    spec:
      containers:
        - name: mlops-lab
          image: ghcr.io/utkarshp845/mlops-lab:latest  # replaced by CI with sha tag
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
