apiVersion: v1
kind: Service
metadata:
  name: mlops-lab
  namespace: mlops
spec:
  selector:
    app: mlops-lab
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
